export enum API_CONFIG {
  REGISTER = '/oauth/register',
  LOGIN = '/oauth/login',
  VERIFY_OTP = '/oauth/verify',
  RESET_ACTIVATION = '/oauth/reset-activation',
  ACCESS_TOKEN = '/oauth/access-token',
  LOGOUT = '/oauth/logout',
  DOCTORS = '/doctors',
  DOCTOR = '/doctor',
  APPOINTMENTS = '/appointments',
  NOTIFICATION_DEVICE = '/notification/device',
  PRE_CONSULTATION = '/pre-consultation',
  SYMPTON = '/symptom',
  REVIEW = '/review',
  SYMPTON_DETAIL = '/symptom-detail',
  PLAYERS = '/players',
  START_CALL = '/call/start-call',
  STOP_CALL = '/call/stop-call',
  UPDATE_CALL = '/call',
  ADD_CARD = '/card',
  WALLET = '/wallet',
  TOP_UP = '/wallet/topup',
  PATIENT_SIGN_UP = '/api/auth/patientSignUp',
  CLINIC = '/api/clinic/all',
  CLINIC_DOCTORS = '/api/clinic/doctors',
  LOGIN_DOCTOR = '/api/auth/login',
  INVOICE = '/invoice',
  REGISTER_STATUS = '/api/auth/registerStatus',
  MEDICAL_HISTORY = '/medical-history',
  CHAT_LIST = '/chat/list',
  START_CHAT = '/chat/start-chat',
  STOP_CHAT = '/chat/stop-chat',
  CHAT = '/chat',
  PROFILE = '/profile/',
  CALL_BACK = '/call/callback',
  APPOINTMENT_UPCOMING = '/appointments/upcoming/patient/',
  APPOINTMENT_PAST = '/appointments/past/patient/',
  SEARCH_DOCTOR = '/doctors/search',
  TRANSACTION = '/transaction',
  SPECIALTIES = '/specialties',
  NEWS = '/articles',
  USER_STATUS = '/user-status',
  NOTIFICATION = '/notification/all',
  AREA_CODE = '/areacodes',
  WELCOME_TEXT = '/settings/welcome-text',
}

export enum API_STATUS {
  UNAUTHORIZE = 401,
}
